ports:
  - port: 3000
    onOpen: open-preview

tasks:
  - before: |
      export FLASK_APP=api.py
      export FLASK_ENV=development
    init: |
      pip install flask pytest
    command: |
      flask run

